language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git --recursive
  - cd ZendSkeletonApplication
  - rm config/application.config.php && cp ../DoctrineORMModule/.travis/application.config.php config/
  - cp ../DoctrineORMModule/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - rm -rf vendor/doctrine/DoctrineORMModule
  - cp -r ../DoctrineORMModule vendor/doctrine/
  - cp ../DoctrineORMModule/.travis/travis.doctrine_orm.local.config.php config/autoload/
  - mysql -e 'create database travis_test;'

script:
  - ./vendor/doctrine/DoctrineORMModule/.travis/run-cli.sh
  - cd vendor/doctrine/DoctrineORMModule/tests
  - phpunit
